<?php

namespace app\webcontroller\controller;

use think\Controller;
use think\Request;
use think\Db;

class Auctioning extends Common
{
    private $model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->model=new \app\common\model\Goods();
    }
    /**
     * 显示资源列表
     *拍卖中的商品列表
     * @return \think\Response
     */
    public function index()
    {
        //定义数据表格
        $table = [
            ['type' => 'numbers', 'title' => '序号'],
            ['field' => 'goods_name','title' => '商品名称','align'=>'center','width' => 150,],
            ['field'=>  'cname','title'=>'分类','align'=>'center','width' => 100,],
            ['field'=>  'name','title'=>'归属者','align'=>'center','width' => 100,],
            ['field'=>  'acname','title'=>'作品来源','align'=>'center','width' => 100,],
//            ['field'=>  'volume','title'=>'数量','align'=>'center','width' => 100,],
            ['field'=>  'decade','title'=>'年代','align'=>'center','width' => 100,],
//            ['field'=>  'source','title'=>'作品来源','align'=>'center','width' => 100,],
            ['field'=>  'decoration','title'=>'作品状态','align'=>'center','width' => 100,'templet' => '#tb-decoration'],


            ['field' => 'image', 'title' =>'封面图','align'=>'center', 'width' => 100,'templet' => '#tb-image'],
            ['field' => 'starting_price','title' => '起拍价','align'=>'center','width' => 80,],
            ['field' => 'range_price','title' => '加价幅度','align'=>'center','width' => 100,],
//            ['field' => 'sort','title' => '排序','align'=>'center','width' => 80,],
            ['field' => 'start_time','title' => '开始时间','align'=>'center','width' => 160,],
            ['field' => 'end_time','title' => '结束时间','align'=>'center','width' => 160,],
            ['field' => 'status','title' => '状态','align'=>'center','width' => 100,'templet' => '#tb-status'],
            //操作标签
//            ['fixed'   => 'right','title'   => '操作','width'   => 178,'align'   => 'center','toolbar' => '#tb-action',],
        ];


        $this->assign('table', json_encode($table));

        return $this->fetch();
    }

    /**
     * 数据列表
     * @param string
     * @return json
     */
    public function getData($limit)
    {
        $name = '';
        $data = $this->request->get();
        if(!empty($data['key']['name'])){
            $name = trim($data['key']['name']);
        }

        if($name){
            $data = $this->model
                ->field('goods.*,cates.cname,artist.name,artist_class_id,artist_class.name as acname')
                ->where('name','like',$name.'%')
                ->where('start_time','<',date('Y-m-d H:i:s',time()))
                ->where('end_time','>',date('Y-m-d H:i:s',time()))
                ->join('artist','goods.artist_id=artist.id','LEFT')
                ->join('cates','goods.cates_id=cates.id','LEFT')
                ->join('artist_class','artist_class.id=artist.artist_class_id','LEFT')
                ->order('create_time desc,sort asc')
                ->paginate($limit)->toArray();

        }else{
            $data = $this->model
                ->field('goods.*,cates.cname,artist.name,artist_class_id,artist_class.name as acname')
                ->where('start_time','<',date('Y-m-d H:i:s',time()))
                ->where('end_time','>',date('Y-m-d H:i:s',time()))
                ->join('cates','goods.cates_id=cates.id','LEFT')
                ->join('artist','goods.artist_id=artist.id','LEFT')
                ->join('artist_class','artist_class.id=artist.artist_class_id','LEFT')
                ->order('goods.create_time desc,goods.sort asc')
                ->paginate($limit)->toArray();
        }
        return $this->result_layui($data['data'], 200, '分类信息', $data['total']);
    }



    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        // 判断当前操作
        if ($this->request->isAjax()) {
            $request = input();
            if(!empty($request['image'])){
                $request['image'] = implode(',',$request['image']);
            }
            return $this->addAction($request, $this->model);
        }
        $cates=Db::table('cates')->field('id,cname')->select();
        return $this->fetch('createEdit',['cates'=>$cates]);
    }




    /**
     * 编辑状态
     * @param $request
     * @return json
     */
    public function updatestate(){
        if ($this->request->isAjax() && $this->request->has('id')) {
            $data = $this->request->post();
            $this->model->where('id', $data['id'])->update(['status' => $data['status']]);
            return $this->result('', 200, '修改成功');
        }
        return $this->result('', 400, '修改失败');
    }
}
