<?php

namespace app\webcontroller\controller;

use think\Controller;
use think\Request;
use think\Db;

class GoodsOffer extends Common
{
    private $model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->model=new \app\common\model\GoodsOffer();
    }

    public function index()
    {
        //定义数据表格
        $table = [
            ['type' => 'numbers', 'title' => '序号'],
            ['field' => 'goods_name','title' => '商品名称','align'=>'center','width' => 280,],
            ['field' => 'member_name','title' => '会员名称','align'=>'center','width' => 100,],
            ['field' => 'create_time','title' => '出价时间','align'=>'center','width' => 200,],
            ['field' => 'price','title' => '价格','align'=>'center','width' => 120,],
        ];

        $this->assign('table', json_encode($table));

        return $this->fetch();
    }
    
    /**
     * 数据列表 
     * 联表查询 联member表获取nickname,联goods获取goods_name
     * @param string
     * @return json
     */
    public function getData($limit)
    {
        $request = input();
        if(!empty($request['key'])){
            $data = $this->model
                ->field('goods_offer.*,member.nickname as member_name')
                ->field('goods_offer.*,goods.goods_name')
                ->join('member','goods_offer.member_id=member.id','LEFT')
                ->join('goods','goods_offer.goods_id=goods.id','LEFT')
                ->where('member.nickname','like',"%".$request['key']['nickname']."%")
                ->where('goods.goods_name','like',"%".$request['key']['goods_name']."%")
                ->order('create_time desc')

                ->paginate($limit)
                ->toArray();
        }else{
            $data = $this->model
                ->field('goods_offer.*,member.nickname as member_name')
                ->field('goods_offer.*,goods.goods_name')
                ->join('member','goods_offer.member_id=member.id','LEFT')
                ->join('goods','goods_offer.goods_id=goods.id','LEFT')
                ->order('goods_offer.create_time desc')

                ->paginate($limit)
                ->toArray();
        }
        return $this->result_layui($data['data'], 200, '分类信息', $data['total']);
      
    }

}
