<?php
/**
 * 订单管理
 * Created by PhpStorm.
 * User: Vernon
 * @Time: 2018/7/12   16:32
 */
namespace app\webcontroller\controller;

use think\Db;

class Orders extends Common{
    private $model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model=new \app\common\model\Orders();
    }

    /**
     * 首页
     * @param $request
     * @return json
     */
    public function index(){
        //定义数据表格
        $table = [
            ['type' => 'numbers', 'title' => '序号'],
            ['field' => 'goods_name', 'title' =>'拍品名称','align'=>'center', 'width' => 220],
            ['field' => 'cover_plan', 'title' =>'拍品图片','align'=>'center', 'width' => 100,'templet' => '#tb-image'],
            ['field' => 'end_price', 'title' =>'成交价','align'=>'center', 'width' => 100],
            ['field' => 'nickname', 'title' =>'买家','align'=>'center', 'width' => 100],
            ['field' => 'logistics', 'title' =>'物流公司','align'=>'center', 'width' => 100,'templet'=>'#tb-logistics'],
            ['field' => 'order_sn', 'title' =>'订单编号','align'=>'center', 'width' => 200],
            ['field' => 'status', 'title' =>'订单状态','align'=>'center', 'width' => 100],
            ['field' => 'create_time', 'title' =>'时间','align'=>'center', 'width' => 180],
            //操作标签
//            ['fixed' => 'right','title' => '操作','width' => 178,'align' => 'center','toolbar' => '#tb-action',],
            ['title' => '操作','width' => 178,'align' => 'center','toolbar' => '#tb-action',],

        ];

        $this->assign('table', json_encode($table));

        return $this->fetch();
    }

    /**
     * 新增功能
     */
    public function create()
    {
        // 判断当前操作
        if ($this->request->isAjax()) {

            $request = input();
            
            return $this->addAction($request, $this->model);

        }
        return $this->fetch('createEdit');
    }

    /**
     * 订单详情
     */
    public function info($id)
    {
        if ($this->request->isAjax()) {
            $request = input();
        }

        $data = Db::table('orders')
            ->where('id',$id)
            ->find();

        $goods = Db::table('goods')
            ->where('id',$data['g_id'])
            ->find();

        $my_auction = Db::table('my_auction')
            ->where('goods_id',$data['g_id'])
            ->where('member_id',$data['m_id'])
            ->find();

        $data['start_time'] = $goods['start_time'];
        $data['end_time'] = $goods['end_time'];
        $data['bond'] = $goods['bond'];
        $data['bond_status'] = $my_auction['bond_status'];
        $data['logistics_time'] =  date('Y-m-d H:i:s',$data['logistics_time']);
        $data['pay_time'] =  date('Y-m-d H:i:s',$data['pay_time']);
        $data['confirm_time'] =  date('Y-m-d H:i:s',$data['confirm_time']);
        $data['image'] =  explode(',', $goods['image']);
        $this->assign('data', $data);
        // p($data);
        return $this->fetch('info');
    }

    /**
     * 编辑
     * @param $request
     * @return json
     */
    public function edit($id)
    {

        if ($this->request->isAjax()) {
//            dump($id);
            $request = input();
//            dump($request);
            $request['logistics_time'] = time();
            $request['status'] = 3;
            $request['remind'] = 0;
            $request['fahuo'] = 1;
            //查当前ID 订单 的商品id
            $g_id=Db::table('orders')->where('id',$request['id'])->value('g_id');
            //发货修改商品的状态 为已发货
            if(!empty($g_id)){
            Db::table('goods')->where('id',$g_id)->update(['auctionstatus'=>5]);
             }
            return $this->editActon($request, $this->model);
        }

        $data = $this->model->find($id);
//        dump($data);
        $this->assign('data', $data);

        return $this->fetch('createEdit');
    }

    /**
     * 删除
     * @param $request
     * @return json
     */
    public function delete()
    {
        if ($this->request->isAjax() && $this->request->has('id')) {
            $id = $this->request->post('id');

            $data = $this->model->get($id);

            if (!$data) {
                return $this->result('', 400, '当前数据不存在！删除失败');
            }

            $result = $data->delete();

            if ($result == FALSE) {
                return $this->result('', 400, $data->getError());
            }

            return $this->result('', 200, '删除成功');
        }

        return $this->result('', 400, '删除失败');
    }

    /**
     * 获取数据
     * @param $request
     * @return json
     */
    public function getData($limit)
    {
        $request = input();
        if(!empty($request['key'])){
            if(!empty($request['key']['nickname'])){
                $where['b.phone|b.nickname'] = array('like','%'.$request['key']['nickname'].'%');
            }
            if(!empty($request['key']['order_sn'])){
                $where['a.order_sn'] = $request['key']['order_sn'];
            }
            if($request['key']['status'] != ''){
                $where['a.status'] = $request['key']['status'];
            }

            if(empty($request['key']['nickname']) && empty($request['key']['order_sn']) && empty($request['key']['status'])){
                $where = '';
            }
            $data = $this->model
                ->alias('a')
                ->join('member b','a.m_id = b.id')
                ->where($where)
                ->order('create_time desc')
                ->field('a.*,b.nickname')
                ->paginate($limit)
                ->toArray();
        }else{
            $data = $this->model
                ->alias('a')
                ->join('member b','a.m_id = b.id')
                ->order('create_time desc')
                ->field('a.*,b.nickname')
                ->paginate($limit)
                ->toArray();
        }

        return $this->result_layui($data['data'], 200, '分类信息', $data['total']);
    }

    /**
     * 编辑状态
     * @param $request
     * @return json
     */

    public function updatestate(){
        if ($this->request->isAjax() && $this->request->has('id')) {
            $data = $this->request->post();
            $this->model->where('id', $data['id'])->update(['status' => $data['status']]);
            return $this->result('', 200, '修改成功');
        }
        return $this->result('', 400, '修改失败');
    }

    /**
     * 获取提醒 发货的数据 数量
     * webcontroller/orders/tixing
     *
     */
        public function tixing()
        {

            $data=Db::table('orders')
                ->where('status',2)
                ->where('remind',1)
                ->count();
//        halt($data);
            if(!empty($data)){
                return $this->result($data, 200, '有提醒','json');
            }else{
                return $this->result('0',400,'无提醒','json');
            }

        }


}