<?php
/**
 * 订单管理
 * Created by PhpStorm.
 * User: Vernon
 * @Time: 2018/7/12   16:32
 */
namespace app\webcontroller\controller;

class Orders extends Common{
    private $model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model=new \app\common\model\Orders();
    }

    /**
     * 首页
     * @param $request
     * @return json
     */
    public function index(){
        //定义数据表格
        $table = [
            ['type' => 'numbers', 'title' => '序号'],
            ['field' => 'nickname', 'title' =>'会员昵称','align'=>'center', 'width' => 200],
            ['field' => 'order_sn', 'title' =>'订单编号','align'=>'center', 'width' => 200],
            ['field' => 'goods_name', 'title' =>'商品名称','align'=>'center', 'width' => 200],
            ['field' => 'name','title' => '收货人','align'=>'center','width' => 150,],
            ['field' => 'phone', 'title' =>'手机号','align'=>'center', 'width' => 200],
            ['field' => 'address', 'title' =>'收货地址','align'=>'center', 'width' => 200],
            ['field' => 'status','title' => '状态','align'=>'center','width' => 100,'templet' => '#tb-status'],
            //操作标签
            ['fixed'   => 'right','title'   => '操作','width'   => 178,'align'   => 'center','toolbar' => '#tb-action',],
        ];

        $this->assign('table', json_encode($table));

        return $this->fetch();
    }

    /**
     * 新增功能
     */
    public function create()
    {
        // 判断当前操作
        if ($this->request->isAjax()) {

            $request = input();

            return $this->addAction($request, $this->model);

        }
        return $this->fetch('createEdit');
    }


    /**
     * 编辑
     * @param $request
     * @return json
     */
    public function edit($id)
    {
        if ($this->request->isAjax()) {
            $request = input();

            return $this->editActon($request, $this->model);
        }
        $data = $this->model->find($id);

        $this->assign('data', $data);

        return $this->fetch('createEdit');
    }

    /**
     * 删除
     * @param $request
     * @return json
     */
    public function delete()
    {
        if ($this->request->isAjax() && $this->request->has('id')) {
            $id = $this->request->post('id');

            $data = $this->model->get($id);

            if (!$data) {
                return $this->result('', 400, '当前数据不存在！删除失败');
            }

            $result = $data->delete();

            if ($result == FALSE) {
                return $this->result('', 400, $data->getError());
            }

            return $this->result('', 200, '删除成功');
        }

        return $this->result('', 400, '删除失败');
    }

    /**
     * 获取数据
     * @param $request
     * @return json
     */
    public function getData($limit)
    {
        $request = input();
        if(!empty($request['key'])){
            if(!empty($request['key']['nickname'])){
                $where['b.phone|b.nickname'] = array('like','%'.$request['key']['nickname'].'%');
            }
            if(!empty($request['key']['order_sn'])){
                $where['a.order_sn'] = $request['key']['order_sn'];
            }
            if($request['key']['status'] != ''){
                $where['a.status'] = $request['key']['status'];
            }
            $data = $this->model
                ->alias('a')
                ->join('member b','a.m_id = b.id')
                ->where($where)
                ->order('create_time desc')
                ->field('a.*,b.nickname')
                ->paginate($limit)
                ->toArray();
        }else{
            $data = $this->model
                ->alias('a')
                ->join('member b','a.m_id = b.id')
                ->order('create_time desc')
                ->field('a.*,b.nickname')
                ->paginate($limit)
                ->toArray();
        }

        return $this->result_layui($data['data'], 200, '分类信息', $data['total']);
    }

    /**
     * 编辑状态
     * @param $request
     * @return json
     */

    public function updatestate(){
        if ($this->request->isAjax() && $this->request->has('id')) {
            $data = $this->request->post();
            $this->model->where('id', $data['id'])->update(['status' => $data['status']]);
            return $this->result('', 200, '修改成功');
        }
        return $this->result('', 400, '修改失败');
    }

}